FROM php:8.1.14-cli-bullseye

RUN docker-php-ext-install pcntl

WORKDIR /opt/eqivo

COPY composer.json .

RUN apt-get update && apt-get install -y unzip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer install --no-dev

COPY . .

ENTRYPOINT ["/opt/eqivo/bin/eqivo"]
