name: CI

on:
  push:
  pull_request:

jobs:
  StaticAnalysis:
    name: StaticAnalysis (PHP ${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        php:
          - 8.1
          - 8.2
          - 8.3
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: composer install
      - run: composer phpstan
      - run: composer psalm -- --output-format=github --shepherd
