name: PHPMD

on:
  push:
  pull_request:
  schedule:
    - cron: '45 7 * * 1'

permissions:
  contents: read

jobs:
  PHPMD:
    name: Run PHPMD scanning
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        php:
          - 8.1
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - name: Create PHPMD directory
        file: path=/usr/share/php/phpmd state=directory

      - name: Install PHPMD
        shell: composer require phpmd/phpmd:@stable -d /usr/share/php/phpmd

      - name: Run PHPMD
        run: /usr/share/php/phpmd/vendor/bin/phpmd . sarif codesize --reportfile phpmd-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: phpmd-results.sarif
          wait-for-processing: true
